// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next";
import { Toaster } from "@/components/ui/sonner";
import { TRPCReactProvider } from "@/trpc/client";
import "./globals.css";
import Head from "next/head"; // import Head for dynamic title and favicon

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Connex AI", // default title
  description: "Generated by Connex AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NuqsAdapter>
      <TRPCReactProvider>
        <html lang="en">
          <Head>
            <link rel="icon" href="favicon.ico" />
            <title>Connex AI</title>
          </Head>
          <body className={`${inter.className} antialiased`}>
            <Toaster />
            {children}
          </body>
        </html>
      </TRPCReactProvider>
    </NuqsAdapter>
  );
}
